Pracice01/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pracice01.Controllers
{
    [Route("[controller]/[action]")]
    public class CalculatorController : Controller
    {
        

        [Route("{firstNumber:int}/{secondNumber:int}")]
        public IActionResult Sum(int firstNumber, int secondNumber)
        {
            ViewData["action"] = RouteData.Values["action"].ToString();
            ViewData["mark"] = '+';
            ViewData["firstNumber"] = firstNumber;
            ViewData["secondNumber"] = secondNumber;
            ViewData["result"] = firstNumber + secondNumber;

            return View("Result");
        }

        [Route("{firstNumber:int}/{secondNumber:int:min(1)}")]
        public IActionResult Divide(int firstNumber, int secondNumber)
        {
            ViewData["action"] = RouteData.Values["action"].ToString();
            ViewData["mark"] = '/';
            ViewData["firstNumber"] = firstNumber;
            ViewData["secondNumber"] = secondNumber;
            ViewData["result"] = firstNumber / secondNumber;

            return View("Result");
        }


    }
}

Pracice01/Controllers/HelloController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pracice01.Controllers
{
    public class HelloController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pracice01/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pracice01.Controllers
{
    [Route("Say")]
    public class MessagesController : Controller
    {
        [Route("{**message}")]
        public IActionResult ShowMessage(string message)
        {
            if (string.IsNullOrEmpty(message))
            {
                ViewData["Message"] = "Message is empty";
            }
            else
            {
                ViewData["Message"] = message;
            }
        
            return View();
        }
    }
}

Pracice01/Views/Calculator/Result.cshtml
@{
    ViewData["Title"] = "Sum";
}

<h1 class="title is-1">@ViewData["action"]</h1>
<h2 class="subtitle is-2">@ViewData["firstNumber"] @ViewData["mark"] @ViewData["secondNumber"]  = @ViewData["result"]</h2>

Pracice01/Views/Hello/Index.cshtml
<h1 class="title is-1">Hello from view with style</h1>

Pracice01/Views/Messages/ShowMessage.cshtml
@{
    ViewData["Title"] = "ShowMessage";
}

<h1 class="title is-1">@ViewData["Message"]</h1>

Pracice01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hello from view</title>
    <link rel="stylesheet" href="~/css/bulma.min.css">
</head>
<body>
<div class="container">
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <strong class="title">My app</strong>
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                @Html.ActionLink("10+5", "Sum", "Calculator", new { firstNumber = 10, secondNumber = 5 }, new { @class = "navbar-item" })
                @Html.ActionLink("10+23", "Sum", "Calculator", new { firstNumber = 10, secondNumber = 23 }, new { @class = "navbar-item" })
            </div>
        
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">                            
                    </div>
                </div>
            </div>
        </div>

    </nav>
</div>

<div class="container">
    @RenderBody()
</div>
</body>
</html>